package org.peter.es.query.builder;

public enum QueryBuilderName {
    FQ, PAGE_START, PAGE_SIZE, ROUTING,EXCLUDE,PREFIX,
    POLYGON, SORT, SORT_MODE, INCLUDE, HL,AGGREGATION, RANGE_AGGREGATION, GEO, MULTIPLE_OR,
    Q, MULTIPLE_AND, WILDCARD, RANGE_START, RANGE_END, ID, RESCORE_ID, RESCORE
}
